[book]
authors = ["Frequency"]
language = "en"
multilingual = false
src = "pages"
title = "Frequency Documentation"

[preprocessor.local]
command = "node preprocessor.mjs"

[output.html]
no-section-label = true
copy-fonts = false                                                                   # Switched to custom fonts
site-url = "/pages/"
git-repository-url = "https://github.com/LibertyDSNP/frequency-docs"
edit-url-template = "https://github.com/LibertyDSNP/frequency-docs/blob/main/{path}"
preferred-dark-theme = "coal"
additional-css = ["css/extended.css"]

# https://github.com/Michael-F-Bryan/mdbook-linkcheck
[output.linkcheck]
exclude = [
  'github\.com/LibertyDSNP/frequency-docs',
  'github\.com/LibertyDSNP/frequency/releases',
  'github\.com/LibertyDSNP/frequency',
  'twitter\.com',
  'www\.frequency\.xyz',
]
follow-web-links = true
traverse-parent-directories = false

[output.html.fold]
enable = true
