name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up mdBook 📚
        uses: ./.github/workflows/common/set-up-mdbook

      - name: Build mdBook 📚
        run: mdbook build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages
          folder: ./book/html
